add getChipId function and examples how to use it
107-systems/107-Arduino-BMP388 pull request #5
Opened 2020-10-10 15:21 UTC by generationmake

Hi @aentinger 
during bring up of my board with the BMP388 I came across some self test function. One is to check the chip ID of the BMP388. So I added this function to the library. I also added two examples. The first shows only the usage of the getChipId function. The second implements the self-test of Bosch application note https://www.bosch-sensortec.com/media/boschsensortec/downloads/application_notes_1/bst-mps-an006.pdf

2020-10-12 03:58 UTC, aentinger requested changes
Good morning @generationmake :coffee: Thank you very much for your PR, it looks very good already, I've just remarked on a couple of minor issues and kindly ask you to rectify them.

2020-10-12 03:58 UTC, aentinger commented on examples/BMP388-self-test/BMP388-self-test.ino
> +//  Serial.print(pressure_hpa);
Please remove the outcommented code from the example.

2020-10-12 03:58 UTC, aentinger commented on examples/BMP388-self-test/BMP388-self-test.ino
> +volatile bool measurement_done;
I suggest immediate initialisation with an initial value, as usually all variables should be assigned a value upon declaration (good defensive coding practive), e.g.
```C++
volatile bool measurement_done = false;
volatile double measurement_pressure_hpa = 0.0;
...
```

2020-10-12 03:58 UTC, aentinger commented on examples/BMP388-self-test/BMP388-self-test.ino
> +  measurement_done=0;
While this statement works due to the internal conversion of `0` to `false` and `!= 0` to `true` it's not a good coding practice. I suggest to directly assign the boolean type `false` here.
```C++
measurement_done = false;
```

2020-10-12 03:58 UTC, aentinger commented on examples/BMP388-self-test/BMP388-self-test.ino
> +  while(measurement_done==0);
... and here to check for
```C++
while(!measurement_done) { };
```
In short: Use boolean value constants for boolean variables (everywhere).

2020-10-12 03:58 UTC, aentinger commented on examples/BMP388-self-test/BMP388-self-test.ino
> +  chip_id=bmp388.getChipId();
This is just a very minor point, but: C++ allows declaration of the variable anywhere in your function before the first usage, they need not be declared at the start of the scope. This is a leftover from C. I'd write instead:
```C++
uint8_t const chip_id = bmp388.getChipId();
```
Same is valid for the other example.

2020-11-05 05:23 UTC, aentinger commented
Good morning @generationmake :wave: :coffee: 

When do you have time to finalise this PR? Would love to merge it in rather sooner than later :wink:

2020-11-05 23:16 UTC, generationmake commented
Hi @aentinger 
I added the requested changes.
Sorry for the delay.

2020-11-06 05:26 UTC, aentinger approved these changes
Thank you @generationmake :rocket:

2020-11-06 05:26 UTC, merged